package earmark

import (
	"encoding/json"
	"os"
	"testing"

	"github.com/nbd-wtf/go-nostr"
)

// fixturePath is shared with the Android test suite. One file, read by both
// implementations — a fixture that lives in only one language proves nothing
// about the other.
const fixturePath = "../earmarks-mobile/app/src/test/resources/giftwrap_fixture.json"

type crossClientFixture struct {
	Comment         string          `json:"_comment"`
	SenderPrivKey   string          `json:"sender_priv_key"`
	SenderPubKey    string          `json:"sender_pub_key"`
	RecipientPriv   string          `json:"recipient_priv_key"`
	RecipientPubKey string          `json:"recipient_pub_key"`
	ExpectedPayload string          `json:"expected_payload"`
	GiftWrap        json.RawMessage `json:"gift_wrap"`
}

const (
	fixtureSenderPriv    = "315e59ff51cb9209768cf7da80791ddcaae56ac9775eb25b6dee1234bc5d2268"
	fixtureRecipientPriv = "a1e37752c9fdc1273be53f68c5f74be7c8905728e8de75800b94262f9497c86e"
)

// TestCrossClientGiftWrapFixture verifies the Go implementation still unwraps
// the committed fixture. Paired with GiftWrapTest on the Android side, which
// unwraps the same bytes, this is what keeps the two clients able to talk.
//
// Set EARMARK_REGENERATE_FIXTURE=1 to rewrite it. Doing so is a protocol change
// and both sides must be re-verified.
func TestCrossClientGiftWrapFixture(t *testing.T) {
	if os.Getenv("EARMARK_REGENERATE_FIXTURE") == "1" {
		writeFixture(t)
	}
	data, err := os.ReadFile(fixturePath)
	if err != nil {
		t.Skipf("fixture not present: %v", err)
	}
	var fx crossClientFixture
	if err := json.Unmarshal(data, &fx); err != nil {
		t.Fatalf("fixture is not valid JSON: %v", err)
	}
	var gw nostr.Event
	if err := json.Unmarshal(fx.GiftWrap, &gw); err != nil {
		t.Fatalf("gift wrap is not a valid event: %v", err)
	}
	sender, payload, err := unwrapPayload(fx.RecipientPriv, &gw)
	if err != nil {
		t.Fatalf("unwrapPayload: %v", err)
	}
	if sender != fx.SenderPubKey {
		t.Errorf("sender = %s, want %s", sender, fx.SenderPubKey)
	}
	if string(payload) != fx.ExpectedPayload {
		t.Errorf("payload mismatch\n got: %s\nwant: %s", payload, fx.ExpectedPayload)
	}
	// The envelope must survive as a channel post with its file key intact —
	// that key is the entire point of the message.
	env, err := decodeEnvelope(payload)
	if err != nil {
		t.Fatalf("decodeEnvelope: %v", err)
	}
	if env.Type != EnvelopePost || env.Earmark == nil || env.Earmark.Blossom == nil {
		t.Fatalf("fixture is not a usable post envelope: %+v", env)
	}
	if env.Earmark.Blossom.Key == "" {
		t.Error("file key did not survive the round trip")
	}
}

func writeFixture(t *testing.T) {
	t.Helper()
	senderPub, err := nostr.GetPublicKey(fixtureSenderPriv)
	if err != nil {
		t.Fatal(err)
	}
	recipientPub, err := nostr.GetPublicKey(fixtureRecipientPriv)
	if err != nil {
		t.Fatal(err)
	}
	payload := `{"v":1,"chan":"deadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeef",` +
		`"type":"post","posted_at":1712350000,"earmark":{"artist":"John Coltrane",` +
		`"album":"A Love Supreme","title":"Resolution","ts":1712345678,` +
		`"blossom":{"key":"c2VjcmV0LWtleS1oZXJlLWZvci10ZXN0aW5nLTEyMzQ1Ng==","ext":".flac",` +
		`"chunks":[{"index":0,"sha256":"abc123","size":42,` +
		`"servers":["https://blossom.towerofsong.ca"]}]}}}`

	gw, err := wrapPayload(fixtureSenderPriv, recipientPub, []byte(payload))
	if err != nil {
		t.Fatal(err)
	}
	gwJSON, err := json.Marshal(gw)
	if err != nil {
		t.Fatal(err)
	}
	fx := crossClientFixture{
		Comment: "Generated by earmark-core's TestCrossClientGiftWrapFixture with " +
			"EARMARK_REGENERATE_FIXTURE=1. Read by both the Go and Android test " +
			"suites so each proves it can read what the other writes. Do not edit by hand.",
		SenderPrivKey:   fixtureSenderPriv,
		SenderPubKey:    senderPub,
		RecipientPriv:   fixtureRecipientPriv,
		RecipientPubKey: recipientPub,
		ExpectedPayload: payload,
		GiftWrap:        gwJSON,
	}
	out, err := json.MarshalIndent(fx, "", "  ")
	if err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(fixturePath, append(out, '\n'), 0o644); err != nil {
		t.Fatal(err)
	}
	t.Logf("regenerated %s", fixturePath)
}
