package com.derpy.earmarks.nostr

import org.json.JSONObject
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNotEquals
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * NIP-59 gift wrap, verified against the Go implementation.
 *
 * `giftwrap_fixture.json` is generated by `earmark-core`'s
 * `TestCrossClientGiftWrapFixture` and read by both test suites — the Go one
 * proves Go can still read it, this one proves Android can. A fixture that
 * lived in only one language would prove nothing about the other.
 */
class GiftWrapTest {

    private fun fixture(): JSONObject {
        val stream = javaClass.classLoader!!.getResourceAsStream("giftwrap_fixture.json")
            ?: error("giftwrap_fixture.json missing — regenerate it from earmark-core")
        return JSONObject(stream.bufferedReader().readText())
    }

    // --- Cross-client ---------------------------------------------------------

    @Test
    fun unwrapsAGiftWrapProducedByGo() {
        val fx = fixture()
        val gw = fx.getJSONObject("gift_wrap")

        val result = GiftWrap.unwrap(fx.getString("recipient_priv_key"), gw)
            ?: error("could not unwrap a gift wrap produced by the Go implementation")

        assertEquals(
            "sender must be the seal's pubkey",
            fx.getString("sender_pub_key"), result.senderPubKey
        )
        assertEquals(fx.getString("expected_payload"), result.content)
    }

    /** The file key is the entire reason a channel post exists. */
    @Test
    fun theFileKeySurvivesTheTripFromGo() {
        val fx = fixture()
        val result = GiftWrap.unwrap(fx.getString("recipient_priv_key"), fx.getJSONObject("gift_wrap"))!!
        val envelope = JSONObject(result.content)
        val blossom = envelope.getJSONObject("earmark").getJSONObject("blossom")

        assertEquals("post", envelope.getString("type"))
        assertTrue("file key is missing", blossom.getString("key").isNotEmpty())
        assertEquals(".flac", blossom.getString("ext"))
    }

    @Test
    fun aStrangerCannotUnwrapGosGiftWrap() {
        val fx = fixture()
        val stranger = "98a5902fd67518a0c900f0fb62158f278f94a21d6f9d33d30cd3091195500311"
        assertNull(GiftWrap.unwrap(stranger, fx.getJSONObject("gift_wrap")))
    }

    /**
     * The published event must not name the real sender. If it does, gift wrap
     * is buying nothing and the whole transport choice was pointless.
     */
    @Test
    fun goSGiftWrapDoesNotNameTheSender() {
        val fx = fixture()
        val gw = fx.getJSONObject("gift_wrap")
        val senderPub = fx.getString("sender_pub_key")

        assertNotEquals("the wrapper is signed by the real sender", senderPub, gw.getString("pubkey"))
        assertTrue(
            "the sender's pubkey appears in the published event",
            !gw.toString().contains(senderPub)
        )
    }

    // --- Round trip -----------------------------------------------------------

    @Test
    fun wrapAndUnwrapRoundTrip() {
        val alice = "315e59ff51cb9209768cf7da80791ddcaae56ac9775eb25b6dee1234bc5d2268"
        val bob = "a1e37752c9fdc1273be53f68c5f74be7c8905728e8de75800b94262f9497c86e"
        val alicePub = Nip44.derivePubKeyHex(alice)
        val bobPub = Nip44.derivePubKeyHex(bob)

        val payload = """{"v":1,"chan":"abc","type":"leave","left_at":1712351111}"""
        val gw = GiftWrap.wrap(alice, bobPub, payload)

        assertEquals(GiftWrap.GIFT_WRAP_KIND, gw.getInt("kind"))
        assertEquals(bobPub, gw.getJSONArray("tags").getJSONArray(0).getString(1))

        val result = GiftWrap.unwrap(bob, gw)!!
        assertEquals(alicePub, result.senderPubKey)
        assertEquals(payload, result.content)
    }

    @Test
    fun ourGiftWrapDoesNotNameTheSenderEither() {
        val alice = "315e59ff51cb9209768cf7da80791ddcaae56ac9775eb25b6dee1234bc5d2268"
        val alicePub = Nip44.derivePubKeyHex(alice)
        val bobPub = "89174fc252d16ee01474b0685550a19578cf2ce18359637a181a5b9941b9c627"
        val chanId = "deadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeef"

        val gw = GiftWrap.wrap(alice, bobPub, """{"v":1,"chan":"$chanId","type":"post"}""")
        val wire = gw.toString()

        assertTrue("sender pubkey leaked", !wire.contains(alicePub))
        assertTrue("channel id leaked", !wire.contains(chanId))
    }

    /** Each wrap must use a fresh throwaway key, or wraps become linkable. */
    @Test
    fun eachWrapUsesAFreshEphemeralKey() {
        val alice = "315e59ff51cb9209768cf7da80791ddcaae56ac9775eb25b6dee1234bc5d2268"
        val bobPub = "89174fc252d16ee01474b0685550a19578cf2ce18359637a181a5b9941b9c627"
        val a = GiftWrap.wrap(alice, bobPub, """{"v":1,"chan":"x","type":"post"}""")
        val b = GiftWrap.wrap(alice, bobPub, """{"v":1,"chan":"x","type":"post"}""")
        assertNotEquals(a.getString("pubkey"), b.getString("pubkey"))
    }

    // --- Signature verification ----------------------------------------------

    @Test
    fun verifiesAGenuineEvent() {
        val alice = "315e59ff51cb9209768cf7da80791ddcaae56ac9775eb25b6dee1234bc5d2268"
        val ev = NostrEvent.build(alice, 1, "hello", emptyList())
        assertTrue(GiftWrap.verifyEvent(ev))
    }

    @Test
    fun verifiesGosSignature() {
        assertTrue(
            "cannot verify a signature produced by go-nostr",
            GiftWrap.verifyEvent(fixture().getJSONObject("gift_wrap"))
        )
    }

    /**
     * The signature only covers the id, so swapping content while keeping both
     * must be caught by recomputing the id. Without that check the whole
     * verification is theatre.
     */
    @Test
    fun rejectsContentSwappedUnderAValidSignature() {
        val alice = "315e59ff51cb9209768cf7da80791ddcaae56ac9775eb25b6dee1234bc5d2268"
        val ev = NostrEvent.build(alice, 1, "hello", emptyList())
        ev.put("content", "goodbye")
        assertTrue("content was swapped without detection", !GiftWrap.verifyEvent(ev))
    }

    @Test
    fun rejectsABadSignature() {
        val alice = "315e59ff51cb9209768cf7da80791ddcaae56ac9775eb25b6dee1234bc5d2268"
        val ev = NostrEvent.build(alice, 1, "hello", emptyList())
        ev.put("sig", "00".repeat(64))
        assertTrue(!GiftWrap.verifyEvent(ev))
    }

    @Test
    fun rejectsAWrapThatIsNotAWrap() {
        val alice = "315e59ff51cb9209768cf7da80791ddcaae56ac9775eb25b6dee1234bc5d2268"
        val notAWrap = NostrEvent.build(alice, 1, "just a note", emptyList())
        assertNull(GiftWrap.unwrap(alice, notAWrap))
    }

    // --- Ephemeral keys -------------------------------------------------------

    @Test
    fun generatedKeysAreDistinctAnd32Bytes() {
        val seen = HashSet<String>()
        repeat(50) {
            val k = GiftWrap.generatePrivateKey()
            assertEquals(64, k.length)
            assertTrue("duplicate ephemeral key", seen.add(k))
        }
    }
}
